global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    project: financial-streaming-platform

scrape_configs:
  - job_name: 'data-generator'
    static_configs:
      - targets: ['data-generator:5000']
    metrics_path: /metrics

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9101']

  - job_name: 'spark'
    static_configs:
      - targets: ['spark-processor:4040']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
